# Generated by Django 5.1.1 on 2024-10-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('Software', 'Software'), ('Testing', 'Testing'), ('Cyber-Security', 'Cyber-Security'), ('Finance', 'Finance')], max_length=20)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Senior', 'Senior'), ('Junior', 'Junior'), ('Team Lead', 'Team Lead'), ('Intern', 'Intern')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
