# Generated by Django 5.1.1 on 2024-10-17 03:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Senior', 'Senior'), ('Junior', 'Junior'), ('Team Lead', 'Team Lead'), ('Intern', 'Intern')], max_length=50)),
                ('interviewer_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('business_area', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Software', 'Software'), ('Testing', 'Testing'), ('Cyber-Security', 'Cyber-Security'), ('Finance', 'Finance')], max_length=50)),
                ('message', models.TextField()),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.interviewee')),
            ],
        ),
    ]
