# Generated by Django 4.2.16 on 2024-10-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
