# Generated by Django 4.2.16 on 2024-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_interview_interviewer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
