# Generated by Django 5.1.1 on 2024-10-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0005_alter_interview_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="interviewee",
            field=models.CharField(max_length=100),
        ),
        migrations.RenameField(
            model_name="interview",
            old_name="message",
            new_name="additional_notes",
        ),
        migrations.RenameField(
            model_name="interview",
            old_name="interviewer_name",
            new_name="interviewer",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="interview_id",
        ),
        migrations.AlterField(
            model_name="interview",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Interviewee",
        ),
    ]
