# Generated by Django 5.1.1 on 2024-11-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_interview_interviewee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
