# Generated by Django 5.1.1 on 2024-11-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_interview_interviewee_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interviewee_contact',
            new_name='contact',
        ),
    ]
