# Generated by Django 4.2.16 on 2024-11-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_rename_interviewee_contact_interview_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='contact',
            new_name='email',
        ),
        migrations.AddField(
            model_name='interview',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
