# Generated by Django 4.2.16 on 2024-11-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_interview_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='contact',
        ),
    ]
