# Generated by Django 5.1.1 on 2024-11-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_remove_interview_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='phone',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
