# Generated by Django 5.1.1 on 2024-11-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_interview_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
