# Generated by Django 5.1.1 on 2024-12-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_alter_interview_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
